package com.app.AIRS.kafka;

public enum TopicName {
    ENUMERATION_FOR_INDIVIDUAL_LOCAL,
    ENUMERATION_FOR_CORPORATE_LOCAL,
    ENUMERATION_FOR_INDIVIDUAL_STAGING,
    ENUMERATION_FOR_CORPORATE_STAGING,
    ENUMERATION_FOR_INDIVIDUAL_PROD,
    ENUMERATION_FOR_CORPORATE_PROD,
    ENUMERATION_FOR_MARKET_PROD,
    ENUMERATION_FOR_TRANSPORT_PROD,
    ENUMERATION_FOR_PROPERTY_PROD,
    ENUMERATION_FOR_DRIVER_PROD,
}
